---
permalink: task-recover-and-restore-from-a-disaster-recovery-failover.html 
sidebar: sidebar 
keywords: recover, disaster, snapmanager, hyper-v, fail, secondary, system, storage, powershell, restore, restoring, failover, recovery 
summary: Para se recuperar de um desastre, o SnapManager para Hyper-V deve primeiro fazer failover para um sistema de storage secundário. O failover envolve uma série de etapas manuais no PowerShell. 
---
= Recuperar e restaurar a partir de um failover de recuperação de desastres
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Para se recuperar de um desastre, o SnapManager para Hyper-V deve primeiro fazer failover para um sistema de storage secundário. O failover envolve uma série de etapas manuais no PowerShell.

.Sobre esta tarefa
A maioria dos backups pode ser restaurada para um host alternativo para nas e SAN; no entanto, os backups consistentes com falhas do Windows Server 2008 R2 não podem ser restaurados para um host alternativo.

.Passos
. Se você estiver executando o Data ONTAP 8.1.x, no local secundário, insira as informações da máquina virtual de armazenamento (SVM) para a configuração de protocolo de transporte (TPS) no SnapDrive para o MMC do Windows.
. No sistema de storage secundário, conecte-se a todos os LUNs.
+
Se o sistema de storage secundário estiver em cluster, vá para o nó em que o grupo de cluster, que é o nó proprietário do grupo de armazenamento disponível no cluster de destino, está on-line e, em seguida, conete-se a todos os LUNs desse nó no cluster. Consulte a documentação do SnapDrive para Windows para obter informações sobre o mapeamento de LUNs.

. Dependendo da configuração, execute uma das seguintes ações:
+
|===
| Se o sistema de armazenamento primário for... | Então... 


 a| 
Um host autônomo (SAN)
 a| 
Conete-se a todos os pontos de montagem e LUNs do mesmo tipo no sistema de armazenamento primário.



 a| 
Um host em cluster (SAN)
 a| 
No nó em que o grupo de clusters está online, conete-se a todos os pontos de montagem e LUNs no cluster.



 a| 
Data ONTAP 8.1.x configurado com um único LUN que hospeda VMs em uma SAN (FlexVol volume) de origem
 a| 
Para que as atualizações do SnapMirror sejam bem-sucedidas, você deve criar um segundo LUN menor (10 MB a 100 MB) no FlexVol volume de origem antes de iniciar um backup. No nó em que o grupo de clusters está online, conete-se a todos os pontos de montagem e LUNs no cluster.



 a| 
Um host autônomo ou em cluster (nas)
 a| 
Desmonte o volume de proteção de dados (DP), monte o volume DP como regravável, verifique se o volume tem permissões RWX e, em seguida, crie compartilhamentos CIFS para os diferentes volumes.

|===
. Reconfigure o SnapInfo com base no seu ambiente:
+
|===
| Se a sua configuração for... | Então... 


 a| 
SAN
 a| 
Restaure o LUN SnapInfo da última cópia Snapshot.



 a| 
NAS
 a| 
Monte o diretório SnapInfo.

|===
+
No nas, se ocorrer um erro de acesso negado ou se não for possível navegar para o local de compartilhamento SMB exposto, talvez seja necessário redefinir a lista de controle de acesso no compartilhamento.

+

NOTE: Isso é típico ao usar o Console do Gerenciador de máquinas virtuais (SCVMM) do Centro de sistema e o Agente SMI-S. do Data ONTAP.

. Adicione o sistema de armazenamento secundário ou cluster no SnapManager para MMC Hyper-V e, em seguida, configure-o com o caminho SnapInfo.
. Insira os seguintes cmdlets:
+
.. Digite `Get-VMsFromBackup` para recuperar a lista de VMs presentes nos metadados de backup.
.. Insira `Get-Backup` para obter as cópias de backup de cada VM.


. Para restaurar, utilize `Restore-Backup` com o GUID VM e a cópia de segurança com os seguintes parâmetros:
+
|===
| Para restaurar de... | Digite este comando... 


 a| 
Um host alternativo
 a| 
`Restore-Backup -Server` `Secondary_host_system_or_cluster_name -DisableVerifySnapshot -RestoreToAlternateHost`



 a| 
Um backup listado
 a| 
`Restore-Backup -Server -VirtualMachinePath -SnapShotFilePath @VHD`

|===
+
Para `@VHD`, uma VM pode ter vários VHDs; certifique-se de inserir um par de caminho de origem e de destino especificado para cada VHD.

. Se o sistema host secundário for um cluster, execute as seguintes etapas:
+
.. Verifique se as LUNs nas quais as VMs residem estão online no nó do cluster que é proprietário do grupo de clusters.
.. Use os cmdlets do PowerShell de failover para tornar as VMs altamente disponíveis.






== Exemplos de failover

O exemplo a seguir mostra uma configuração de dois clusters na qual o smhv-cluster-01 é o local principal e o HV-19-cluster é o local secundário:

[listing]
----
PS C:\> Get-VMsFromBackup -Server hv-19-cluster

winxp-x64c-135                593ABA72-B323-4AF7-9AC6-9514F64C0178
csv1-xp-3                     59B85C68-BAFA-4A49-8E85-A201045843F7
vm-w2k8r2sp1                  5A248757-872B-4FE7-8282-91C8E9D45CF9
um10_11_dr                    5AC1B2A8-6603-4F90-98F5-4F2F435AB0C2
winxp-x64c-30                 5B47D3CF-5D96-495D-9BAB-FB394392CF31
winxp-x64c-126                5B57EED1-B4F1-45A3-A649-24C6947CB79C
winxp-x64c-118                5B5D417B-70DC-427C-94BB-97FF81C5B92B
winxp-x64c-122                5BEE26B8-BE57-4879-A28E-9250A6A5EEFC
csv4-w2k3-19                  5D0613E5-B193-4293-8AAD-F8B94A5D851F

PS C:\> Get-Backup -Server hv-19-cluster -ResourceName um10_11_dr

BackupName    : smhv-ccb-ds_04-10-2012_10.37.58
RetentionType : hourly
DatasetName   : smhv-ccb-ds
BackupId      : smhv-ccb-ds_04-10-2012_10.37.58
BackupTime    : 4/10/2012 10:37:58 AM
BackupType    : Application consistent
BackedupVMs   : {um10_11_dr}

PS C:\> Restore-Backup -Server hv-19-cluster -ResourceName
um10_11_dr -BackupName smhv-ccb-ds_04-10-2012_10.37.58
-DisableVerifySnapshot -RestoreToAlternateHost
----
O exemplo a seguir mostra uma operação de restauração SAN para um caminho alternativo para o qual N: É o destino e I: É o caminho LUN de origem:

[listing]
----
PS C:\> Restore-Backup -Resourcename dr-san-ded1
-RestoreToAlternateHost -DisableVerifySnapshot -BackupName san_dr_09-11-2013_10.57.31 -Verbose
-VirtualMachinePath "N:\dr-san-ded1" -SnapshotFilePath "N:\dr-san-ded1" -VHDs @(@{"SourceFilePath" = "I:\dr-san-ded1\Virtual Hard Disks\dr-san-ded1.vhdx"; "DestinationFilePath" = "N:\dr-san-ded1\Virtual Hard Disks\dr-san-ded1"})
----
O exemplo a seguir mostra uma operação de restauração nas para um caminho alternativo para o qual ' 172.17.162.174 é o caminho de compartilhamento SMB de origem e ' 172.17.175.82 é o caminho de compartilhamento SMB de destino:

[listing]
----
PS C:\> Restore-Backup -Resourcename vm_claba87_cifs1
-RestoreToAlternateHost -DisableVerifySnapshot -BackupName ag-DR_09-09-2013_16.59.16 -Verbose
-VirtualMachinePath "\\172.17.175.82\vol_new_dest_share\ag-vm1" -SnapshotFilePath "\\172.17.175.82\vol_new_dest_share\ag-vm1" -VHDs @(@{"SourceFilePath" = "\\172.17.162.174\vol_test_src_share\ag-vm1\Virtual Hard Disks\ag-vm1.vhdx"; "DestinationFilePath" = "\\172.17.175.82\vol_new_dest_share\ag-vm1\Virtual Hard Disks\ag-vm1.vhdx"})
----
*Informações relacionadas*

https://library.netapp.com/ecm/ecm_download_file/ECMP1368826["Guia de backup e recuperação on-line de proteção de dados do Data ONTAP 8.2 para o modo 7"]

http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=30049["Documentação do NetApp: SnapDrive para Windows (versões atuais)"]

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.cdot-famg-cifs/home.html["Referência SMB/CIFS"]
